#!/bin/bash

set -e

. $(dirname $0)/base

WORKDIR "/work/src/${QEMU_SRC_BASENAME}"
RUN patch -p1 -i "${WORK_ROOT}/patch/alpinelinux.diff"
RUN patch -p1 -i "${WORK_ROOT}/patch/do_sendrecvmsg_locked.diff"
